# Generated by Django 2.2.9 on 2020-01-13 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200113_2024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postlike',
            old_name='author',
            new_name='user',
        ),
    ]
